version: '3'

services:
  db:
    build: ./db
    ports:
      - "3306:3306"
  php:
    build: ./php
    ports:
      - "80:80"
    depends_on:
      - db
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - db
      - php
